config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: "pages#about"
  get 'frontpage', to: "pages#front"

  get 'signup', to: "users#new"
  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]

  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_category_relations
  has_many :categories, through: :article_category_relations
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 5000 }
  validates :user_id , presence: true
end

app/models/article_category_relation.rb
class ArticleCategoryRelation < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_category_relations
  has_many :articles, through: :article_category_relations
  validates :name, presence: true, length: { minimum: 3, maximum: 20}, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
        uniqueness: {case_sensitive: false},
        length: { minimum: 3 , maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
        uniqueness: {case_sensitive: false},
        format: { with: VALID_EMAIL_REGEX}

  def full_name
    first_name || last_name ?  "#{first_name} #{last_name}".strip : "#{username}"
  end

  def self.find_by_param(param)
    User.find_by(email: param) || User.find_by(username: param)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  # To get the current user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # To check whether the user is logged in
  def logged_in?
    !!current_user
  end

  # Method to ensure redirection to home page to avoid unauthorized access
  def require_user
    unless logged_in?
      flash[:danger] = "You must be logged in"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @article = Article.new
  end

  def edit
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Your Article has been succefully saved."
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Your article updated succefully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article is deleted successfully"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title,:description, :category_ids => [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You are not authorized!"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

   before_action :require_admin, except: [:index, :show]

   def index
    @categories = Category.paginate(page: params[:page],per_page: 5)
   end

   def new
    @category = Category.new
   end

   def create
    @category = Category.new(category_params)
    if @category.save
     flash[:success] = "Category added successfully!"
     redirect_to categories_path
    else
     render 'new'
    end
   end

   def edit
    @category = Category.find(params[:id])
   end

   def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
     flash[:success] = "Category updated successfully!"
     redirect_to category_path(@category)
    else
     render 'edit'
    end
   end

   def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 2)
   end

   private

   def category_params
    params.require(:category).permit(:name)
   end

   def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
     flash[:danger] = "Admin users only can access"
     redirect_to categories_path
    end
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def front
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_param(params[:session][:param])
    if user and user.authenticate(params[:session][:password])
      flash[:success] = "Welcome #{user.username}" # For the upcoming request
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Please check your login credentials" # For the current view
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Successfully Signed out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit,:update,:show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  before_action :verify_current_user_credentials, only: [:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to alpha-blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Account information updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def index
    @users = User.paginate(:page => params[:page], :per_page => 3)
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "All articles and user information have been deleted"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :first_name, :last_name)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def verify_current_user_credentials
    unless @user.authenticate(params[:user][:password]) #|| current_user.admin?
    flash[:danger] = "Current Password in incorrect."
    render 'edit'
    end
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You are not authorized"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin can access that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    require 'rest-client'
    require 'json'
    require 'date'
    @quote_of_the_day = nil
    def gravatar_for (user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end

    def get_quote_of_the_day
      if @quote_of_the_day && Date.parse(@quote_of_the_day[:date]) == Date.today
        @quote_of_the_day
      else
        response = RestClient.get "http://quotes.rest/qod.json"
        @quote_of_the_day = JSON.parse(response,symbolize_names: true)[:contents][:quotes].first
      end
    end
end

app/views/articles/_articles.html.erb
<% obj.each do |article| %>
 <div class="well">
     <div class="article-title">
         <%= link_to truncate(article.title, length:50), article_path(article) %>

         <% if logged_in? and (current_user == article.user  || current_user.admin? ) %>
             <div class="article-action-buttons">
                 <%= link_to  edit_article_path(article) do %>
                 <%= content_tag :span,"", class: "glyphicon glyphicon-pencil", :aria_hidden => "true" %>
                 <% end%>
                 <%= link_to  article_path(article), method: 'delete', data: {confirm: 'Are you sure want to delete?'} do  %>
                 <%= content_tag :span,"", :class => "glyphicon glyphicon-trash", :aria_hidden => "true" %>
                 <% end %>
             </div>
         <% end %>
     </div>

     <div class="article-description">
         <%= truncate(article.description, length: 200) %>
     </div>
     <% if article.categories.any?  %>
             <p><%= render article.categories %></p>
     <% end %>
     <div class="article-meta-details">
         <div id="left">
             <small><%= "Created By: #{article.user.username}" if article.user%> </small>
         </div>
         <div id="right">
             <small>
                Created: <%= time_ago_in_words article.created_at %> ago,
                Last updated: <%= time_ago_in_words article.updated_at %> ago
            </small>
        </div>
     </div>
 </div>
<% end%>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class='col-xs-12'>
        <%= form_for @article, :html => {class: "form-horizontal", role: "form"} do |f| %>
          <div class="form-group">
              <div class="control-label col-sm-2">
                <%= f.label :title %>
              </div>
              <div class="col-sm-8">
                <%= f.text_field :title , class: "form-control", placeholder: "Title of the Article", autofocus: true %>
              </div>
          </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>        
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description , class: "form-control", rows: 10, placeholder: "Contents" %>
                </div>
            </div>        
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.collection_check_boxes :category_ids,Category.all, :id, :name do |cb|%>
                    <% cb.label( class: "checkbox-inline input_checkbox") {cb.check_box(class: "check_box") + cb.text} %>
                    <% end %>
                    
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit class: "btn btn-primary btn-lg"%>
                </div>
            </div>
            
        <% end %>
         <div class="col-xs-4 col-xs-offset-4">
                [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 style="text-align: center;">Edit Existing article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class = "container" style="min-height:100%">
    <div class="row">
        <div class='col-xs-8 col-xs-offset-2'>
            <h4 class="center">Articles List</h1>
            <div class="center">
                <%= will_paginate %>
            </div>
            <%= render 'articles', obj: @articles %>
            <div class="center">
                <%= will_paginate %>
            </div>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<h1 style="text-align: center">Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h4 class="center">
    Title : <%= @article.title %>
</h4>
<div class="well col-xs-8 col-xs-offset-2">
    <%= simple_format @article.description %>
    <% if @article.categories.any?  %>
        <%= render @article.categories %></p>
    <% end %>
    <div class="article-actions">
        <% if logged_in? and (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit Article", edit_article_path(@article) , class: "btn btn-xs btn-primary"%>
        <%= link_to "Delete Article", article_path(@article), method: 'delete', data: {confirm: "Are you sure wnat to Delete?" }, class: "btn btn-xs btn-danger" %>
        <% end %>
        <%= link_to "View Articles", articles_path, class: "btn btn-xs btn-success" %>
    </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category)%></span> &nbsp;

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_for @category, :html => {class: "form-horizontal", role: "form"} do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      <div class="col-sm-6">
        <%= f.text_field :name , class: "form-control", placeholder: "category name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-primary btn-lg"%>
        </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">List of Categories</h1>
<div align="center">
    <ul class="listing">
    <%= will_paginate %>
    <% @categories.each do |category| %>
        <div class="row">
            <div class="well col-md-4 col-md-offset-4">
                <li class="article-title">
                    <%= link_to category.name, category_path(category)%>
                    <div><%= pluralize category.articles.count,"article" %></div>
                </li>
                
            </div>
        </div>
    <% end %>
    </ul>
    <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h2 align="center">List of articles in <%= @category.name %></h2>
<% if logged_in? and current_user.admin? %>
    <div class="row" align="center">
        <span class="badge"><%= link_to "Edit category name", edit_category_path %></span>
    </div>
<% end %>
<div class="center">
    <%= will_paginate @category_articles %>
</div>
<% # if @user.articles is used then it will getch all. pagination don't work %>
<%= render 'articles/articles', obj: @category_articles %>
<div class="center">
    <%= will_paginate @category_articles %>
</div>

app/views/layouts/_flash_messages.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <% flash.each do |name,message| %>
            <div class="alert alert-<%= name%>">
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, message, :id => "flash_#{name}" if message.is_a?(String) %>
            </div>         
        <% end %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="left-footer">All Rights Reserved.</div>
  <div class="right-footer">Contact us on @support@alpha-blog.com</div>
</footer>

app/views/layouts/_header.html.erb
<header>Alpha-Blog<br/>
<p class="caption">
    Welcome to the world of Bloggers. Write,Rate,Like and Share
</p>
</header>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= frontpage_path%>">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= new_article_path%>">Wanna Write?</a></li>
        <li><a href="<%= current_user ? user_path(current_user) : '#' %> ">I've Shared</a></li>
        <li><a href="<%= articles_path%>">Top Rated</a></li>
        <li><a href="#">Recently Added</a></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
          role="button" aria-haspopup="true" aria-expanded="false">
            Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
              <% if logged_in? and current_user.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Add new category", new_category_path %></li>
              <% end %>
            </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
          role="button" aria-haspopup="true" aria-expanded="false">
            Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View your profile", user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete%></li>
            </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_template1.html.erb
<div class="">
    <%= render 'layouts/header' %>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%# debug(params) if Rails.env.development? %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
    
   <%= render 'layouts/template1' %>
    
</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<head>
</head>
<body>
    <h1>About Page</h1>
</body>
</html>

app/views/pages/front.html.erb
<style media="screen">
  .jumbotron {
    background-image: url(<%= get_quote_of_the_day[:background] %>);
    background-repeat: no-repeat;
    background-position: center
  }
</style>
<div class="jumbotron">
  <h2>Quote for the day</h2>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <p><%= get_quote_of_the_day[:quote]%></p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Alpha Blog</h1>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <p>Welcome to the world of alpha bloggers. The alpha of Blogging sites.</p>
      <p>Where you could write the meaningful blogs.</p>
      <p>
        <a class="btn btn-primary btn-lg" href='<%=signup_path%>' role="button">Get Started</a>
      </p>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div  class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
              <h2 class="panel-title"><%= pluralize(obj.errors.count, "error") %></h2>
            </div>
            <div class="panel-body">
                <ul>
                    <% obj.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
    <div class='col-xs-12'>
        <%= form_for @user, :html => {class: "form-horizontal", role: "form"} do |f| %>
            <div class="form-group">
              <div class="control-label col-sm-2">
                <%= f.label "User Name" %>
              </div>
              <div class="col-sm-6">
                <%= f.text_field :username , class: "form-control", placeholder: "Enter your username", autofocus: true %>
              </div>
            </div>
            <div class="form-group">
              <div class="control-label col-sm-2">
                <%= f.label :first_name %>
              </div>
              <div class="col-sm-3">
                <%= f.text_field :first_name , class: "form-control", placeholder: "Enter your First Name" %>
              </div>
              <div class="control-label col-sm-1">
                <%= f.label :last_name , style: "float: left;" %>
              </div>
              <div class="col-sm-2">
                <%= f.text_field :last_name , class: "form-control", placeholder: "Enter your Last Name", style: "float: left;"%>
              </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :email %>
                </div>
                <div class="col-sm-6">
                    <%= f.text_field :email , class: "form-control", placeholder: "Enter your email id" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :password %>
                </div>
                <div class="col-sm-6">
                    <%= f.password_field :password , class: "form-control", placeholder: "Enter your password" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-primary btn-lg")%>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h2 class="center">Edit User Account Information</h2>
<%= render 'shared/errors', obj: @user %>
<%= render 'form' %>

app/views/users/index.html.erb
<h2 class="center"> Alpha bloggers</h2>
<div class="center">
    <%= will_paginate %>
</div>
<% @users.each do |user| %>
    <div class="row">
        <div class="well col-md-8 col-md-offset-2">
             <div class="article-meta-details">
                <div id="left">
                    <%= link_to gravatar_for(user), user_path(user) %>
                    <small><%= link_to user.username, user_path(user) %></small>
                </div>
                <div id="right">
                    <small><%= pluralize(user.articles.count,"article") %></small>
                    <% if logged_in? and current_user.admin? %>
                    <%= link_to  user_path(user), method: 'delete', data: {confirm: 'Are you sure want to delete?'} do  %>
                                 <%= content_tag :span,"", :class => "glyphicon glyphicon-trash", :aria_hidden => "true" %>
                                 <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
<% end %>
<div class="center">
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h2 class="center">Sign Up</h2>
<%= render 'shared/errors', obj: @user %>

<div class="row">
    <div class='col-xs-12'>
        <%= form_for @user, :html => {class: "form-horizontal", role: "form"} do |f| %>
            <div class="form-group">
              <div class="control-label col-sm-2">
                <%= f.label :username %>
              </div>
              <div class="col-sm-6">
                <%= f.text_field :username , class: "form-control", placeholder: "Enter your username", autofocus: true %>
              </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :email %>        
                </div>
                <div class="col-sm-6">
                    <%= f.text_field :email , class: "form-control", placeholder: "Enter your email id" %>
                </div>
            </div>        
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :password %>        
                </div>
                <div class="col-sm-6">
                    <%= f.password_field :password , class: "form-control", placeholder: "Enter your password" %>
                </div>
            </div>        
                
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit "Sign up", class: "btn btn-primary btn-lg"%>
                </div>
            </div>
            
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<h2 class="center">Welcome to <%= @user.full_name %>'s Page</h2>
<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
    </div>
    <div class="col-md-4 col-md-offset-4 center">
    <h4 align="center"><%= @user.full_name %>'s articles</h4>
    </div>
</div>
<div class="center">
    <%= will_paginate @user_articles %>
</div>
<% # if @user.articles is used then it will getch all. pagination don't work %>
<%= render 'articles/articles', obj: @user_articles %>
<div class="center">
    <%= will_paginate @user_articles %>
</div>